-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema laravel5.5-direct-development
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `laravel5.5-direct-development` DEFAULT CHARACTER SET utf8 ;
-- USE `laravel5.5-direct-development` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `api_token` VARCHAR(512) NULL,
  `permission` VARCHAR(45) NULL,
  `avatar` VARCHAR(256) NULL,
  `phone` VARCHAR(45) NULL,
  `remark` VARCHAR(256) NULL,
  `creator_id` INT NULL,
  `status` INT NULL,
  `login_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insert default user with name "admin" and password "123456" for laravel5.5-direct-development
-- -----------------------------------------------------
INSERT INTO `user` (`name`,`password`,`email`,`permission`) VALUES ('admin','$2y$10$iZOGEWcjdR5u8TZXOtZ6DuPGPC7C6XPfQwzEvCF7W2Oazz6isvsvG','admin@deepnorth.cn','2');
-- -----------------------------------------------------