<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateDwellTimeAllpersonTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('dwell_time_allperson', function(Blueprint $table)
		{
			$table->integer('id', true);
			$table->integer('re_id')->nullable()->comment('People’s feature-id generated by the algorithm');
			$table->integer('dwell_time')->nullable()->comment('People’s dwell time (seconds) in a zone for an hour');
			$table->integer('re_id_count')->nullable()->comment('People’s enter count in a zone and for an hour');
			$table->integer('type_id')->nullable()->default(0);
			$table->integer('model_id')->nullable()->default(0);
			$table->timestamp('create_time')->default(DB::raw('CURRENT_TIMESTAMP'))->index('dwell_time_allperson_create_time_idx')->comment('Video real time (video capture host timezone)');
			$table->timestamp('update_time')->default(DB::raw('CURRENT_TIMESTAMP'))->comment('The record insert to DB time (DB timezone)');
		});
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('dwell_time_allperson');
	}

}
